// Code generated by zenrpc v2.3.3; DO NOT EDIT.

package rpc

import (
	"context"
	"encoding/json"

	"github.com/vmkteam/zenrpc/v2"
	"github.com/vmkteam/zenrpc/v2/smd"
)

var RPC = struct {
	ToolsService struct{ List, Call string }
}{
	ToolsService: struct{ List, Call string }{
		List: "list",
		Call: "call",
	},
}

func (ToolsService) SMD() smd.ServiceInfo {
	return smd.ServiceInfo{
		Methods: map[string]smd.Service{
			"List": {
				Description: `List returns the tools visible to the caller; the catalogue and annotations
are built per role by each tool's own Describe (registry.go).

The role is resolved here rather than in the registry because a caller whose
groups match nothing must get a 403, not an empty catalogue. RPCError turns an
invalid cursor into -32602 instead of zenrpc's blanket -32603.`,
				Parameters: []smd.JSONSchema{
					{
						Name:        "cursor",
						Description: `nextCursor from the previous page; empty for the first`,
						Type:        smd.String,
					},
				},
				Returns: smd.JSONSchema{
					Type:     smd.Object,
					TypeName: "McpToolList",
					Properties: smd.PropertyList{
						{
							Name: "tools",
							Type: smd.Array,
							Items: map[string]string{
								"$ref": "#/definitions/mcp.Tool",
							},
						},
						{
							Name: "nextCursor",
							Description: `NextCursor continues the enumeration. Its absence is the end of it —
there is no other signal, so it must be omitted rather than sent empty.`,
							Type: smd.String,
						},
						{
							Name: "ttlMs",
							Type: smd.Integer,
						},
						{
							Name: "cacheScope",
							Type: smd.String,
						},
					},
					Definitions: map[string]smd.Definition{
						"mcp.Tool": {
							Type: "object",
							Properties: smd.PropertyList{
								{
									Name: "name",
									Type: smd.String,
								},
								{
									Name: "title",
									Type: smd.String,
								},
								{
									Name: "description",
									Type: smd.String,
								},
								{
									Name: "inputSchema",
									Ref:  "#/definitions/json.RawMessage",
									Type: smd.Object,
								},
								{
									Name: "outputSchema",
									Description: `OutputSchema describes the shape of StructuredContent. Declaring one is a
promise: "Servers MUST provide structured results that conform to this
schema", and clients validate against it. SchemaFor builds one from the
same struct the tool returns.`,
									Ref:  "#/definitions/json.RawMessage",
									Type: smd.Object,
								},
								{
									Name: "icons",
									Type: smd.Array,
									Items: map[string]string{
										"$ref": "#/definitions/mcp.Icon",
									},
								},
								{
									Name:     "annotations",
									Optional: true,
									Ref:      "#/definitions/mcp.ToolAnnotations",
									Type:     smd.Object,
								},
							},
						},
						"json.RawMessage": {
							Type:       "object",
							Properties: smd.PropertyList{},
						},
						"mcp.Icon": {
							Type: "object",
							Properties: smd.PropertyList{
								{
									Name: "src",
									Type: smd.String,
								},
								{
									Name: "mimeType",
									Type: smd.String,
								},
								{
									Name: "sizes",
									Type: smd.Array,
									Items: map[string]string{
										"type": smd.String,
									},
								},
								{
									Name: "theme",
									Type: smd.String,
								},
							},
						},
						"mcp.ToolAnnotations": {
							Type: "object",
							Properties: smd.PropertyList{
								{
									Name: "title",
									Type: smd.String,
								},
								{
									Name:     "readOnlyHint",
									Optional: true,
									Type:     smd.Boolean,
								},
								{
									Name:     "destructiveHint",
									Optional: true,
									Type:     smd.Boolean,
								},
								{
									Name:     "idempotentHint",
									Optional: true,
									Type:     smd.Boolean,
								},
								{
									Name:     "openWorldHint",
									Optional: true,
									Type:     smd.Boolean,
								},
							},
						},
					},
				},
			},
			"Call": {
				Description: `Call dispatches an MCP tools/call request.

MCP convention: tool errors are returned in result.IsError=true, never as
JSON-RPC errors — that is why all branches return (result, nil). arguments is
map[string]any (not json.RawMessage) to avoid the zenrpc-gen encoding/json
double-import.`,
				Parameters: []smd.JSONSchema{
					{
						Name:        "name",
						Description: `name of the tool to invoke (api_call)`,
						Type:        smd.String,
					},
					{
						Name:        "arguments",
						Description: `tool-specific JSON arguments`,
						Type:        smd.Object,
					},
				},
				Returns: smd.JSONSchema{
					Type:     smd.Object,
					TypeName: "McpToolCallResult",
					Properties: smd.PropertyList{
						{
							Name: "content",
							Type: smd.Array,
							Items: map[string]string{
								"$ref": "#/definitions/mcp.ContentBlock",
							},
						},
						{
							Name: "structuredContent",
							Description: `StructuredContent is the answer as data rather than as text. A tool that
returns it "SHOULD also return the serialized JSON in a TextContent
block", which is why OKResult fills both: the field is what a client
validates and parses, the text block is what an older one reads.`,
							Type: smd.Object,
						},
						{
							Name: "isError",
							Type: smd.Boolean,
						},
					},
					Definitions: map[string]smd.Definition{
						"mcp.ContentBlock": {
							Type: "object",
							Properties: smd.PropertyList{
								{
									Name: "type",
									Type: smd.String,
								},
								{
									Name: "text",
									Type: smd.String,
								},
								{
									Name: "data",
									Description: `Data is base64, and it has to be: "Binary data MUST be properly encoded",
and raw bytes in a JSON string come out as U+FFFD.`,
									Type: smd.String,
								},
								{
									Name: "mimeType",
									Type: smd.String,
								},
								{
									Name: "uri",
									Description: `The resource_link fields. A link is how a tool points the model at
something in the catalogue instead of inlining it — the model reads the
description and decides whether the resource is worth a resources/read.`,
									Type: smd.String,
								},
								{
									Name: "name",
									Type: smd.String,
								},
								{
									Name: "title",
									Type: smd.String,
								},
								{
									Name: "description",
									Type: smd.String,
								},
								{
									Name: "size",
									Type: smd.Integer,
								},
								{
									Name: "icons",
									Type: smd.Array,
									Items: map[string]string{
										"$ref": "#/definitions/mcp.Icon",
									},
								},
								{
									Name:        "resource",
									Optional:    true,
									Description: `Resource carries a resource inline, for type "resource".`,
									Ref:         "#/definitions/mcp.ResourceContent",
									Type:        smd.Object,
								},
								{
									Name:     "annotations",
									Optional: true,
									Ref:      "#/definitions/mcp.Annotations",
									Type:     smd.Object,
								},
							},
						},
						"mcp.Icon": {
							Type: "object",
							Properties: smd.PropertyList{
								{
									Name: "src",
									Type: smd.String,
								},
								{
									Name: "mimeType",
									Type: smd.String,
								},
								{
									Name: "sizes",
									Type: smd.Array,
									Items: map[string]string{
										"type": smd.String,
									},
								},
								{
									Name: "theme",
									Type: smd.String,
								},
							},
						},
						"mcp.ResourceContent": {
							Type: "object",
							Properties: smd.PropertyList{
								{
									Name: "uri",
									Type: smd.String,
								},
								{
									Name: "mimeType",
									Type: smd.String,
								},
								{
									Name: "text",
									Type: smd.String,
								},
								{
									Name: "blob",
									Type: smd.String,
								},
							},
						},
						"mcp.Annotations": {
							Type: "object",
							Properties: smd.PropertyList{
								{
									Name: "audience",
									Type: smd.Array,
									Items: map[string]string{
										"type": smd.String,
									},
								},
								{
									Name:     "priority",
									Optional: true,
									Type:     smd.Float,
								},
								{
									Name: "lastModified",
									Type: smd.String,
								},
							},
						},
					},
				},
			},
		},
	}
}

// Invoke is as generated code from zenrpc cmd
func (s ToolsService) Invoke(ctx context.Context, method string, params json.RawMessage) zenrpc.Response {
	resp := zenrpc.Response{}
	var err error

	switch method {
	case RPC.ToolsService.List:
		var args = struct {
			Cursor string `json:"cursor"`
		}{}

		if zenrpc.IsArray(params) {
			if params, err = zenrpc.ConvertToObject([]string{"cursor"}, params); err != nil {
				return zenrpc.NewResponseError(nil, zenrpc.InvalidParams, "", err.Error())
			}
		}

		if len(params) > 0 {
			if err := json.Unmarshal(params, &args); err != nil {
				return zenrpc.NewResponseError(nil, zenrpc.InvalidParams, "", err.Error())
			}
		}

		resp.Set(s.List(ctx, args.Cursor))

	case RPC.ToolsService.Call:
		var args = struct {
			Name      string         `json:"name"`
			Arguments map[string]any `json:"arguments"`
		}{}

		if zenrpc.IsArray(params) {
			if params, err = zenrpc.ConvertToObject([]string{"name", "arguments"}, params); err != nil {
				return zenrpc.NewResponseError(nil, zenrpc.InvalidParams, "", err.Error())
			}
		}

		if len(params) > 0 {
			if err := json.Unmarshal(params, &args); err != nil {
				return zenrpc.NewResponseError(nil, zenrpc.InvalidParams, "", err.Error())
			}
		}

		resp.Set(s.Call(ctx, args.Name, args.Arguments))

	default:
		resp = zenrpc.NewResponseError(nil, zenrpc.MethodNotFound, "", nil)
	}

	return resp
}
